#!/bin/bash

apt-get update
apt-get upgrade -y
apt-get install apache2 -y
apt-get install unzip -y

cd /tmp
wget https://github.com/repositorios_com_arquivos_site.zip
cd linux-site
cp -R * /var/www/html/

